version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    container_name: "database"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - storage:/var/lib/postgresql/data
volumes:
  storage:
    driver: local
