version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    container_name: "database"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - storage:/var/lib/postgresql/data

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: "minio"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - mangaservice 
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=hanan
      - MINIO_ROOT_PASSWORD=awiroot123
      - MINIO_DEFAULT_BUCKETS=manga

  backend:
    image: readmanga:v0.0.1
    container_name: readmanga
    ports:
      - 8000:8000
    command: start -p 8000 -c config.json
    volumes:
      - ./config.json:/app/config.json

volumes:
  storage:
    driver: local
  minio_data:
    driver: local

networks:
  mangaservice:
    driver: bridge
