// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpRoute is an autogenerated mock type for the HttpRoute type
type HttpRoute struct {
	mock.Mock
}

// Routes provides a mock function with given fields:
func (_m *HttpRoute) Routes() {
	_m.Called()
}

// NewHttpRoute creates a new instance of HttpRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpRoute {
	mock := &HttpRoute{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
