// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Creational is an autogenerated mock type for the Creational type
type Creational[T interface{}, K interface{}] struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *Creational[T, K]) Create(ctx context.Context, data *T) (K, error) {
	ret := _m.Called(ctx, data)

	var r0 K
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) (K, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *T) K); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(K)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *T) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreational creates a new instance of Creational. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreational[T interface{}, K interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Creational[T, K] {
	mock := &Creational[T, K]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
