// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Creational is an autogenerated mock type for the Creational type
type Creational[T interface{}] struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *Creational[T]) Create(ctx context.Context, data *T) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreational creates a new instance of Creational. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreational[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Creational[T] {
	mock := &Creational[T]{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
