// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	entity "bacakomik/record/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	mysql "bacakomik/repository/mysql"
)

// RepoUserCreational is an autogenerated mock type for the RepoUserCreational type
type RepoUserCreational struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *RepoUserCreational) Create(ctx context.Context, data *entity.User) (int, error) {
	ret := _m.Called(ctx, data)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) (int, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) int); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RepoUserCreational) Delete(ctx context.Context, id int) bool {
	ret := _m.Called(ctx, id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *RepoUserCreational) GetAll(ctx context.Context) []*entity.User {
	ret := _m.Called(ctx)

	var r0 []*entity.User
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	return r0
}

// GetOne provides a mock function with given fields: ctx, id
func (_m *RepoUserCreational) GetOne(ctx context.Context, id int) *entity.User {
	ret := _m.Called(ctx, id)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	return r0
}

// NewApi provides a mock function with given fields:
func (_m *RepoUserCreational) NewApi() *mysql.UserRepository {
	ret := _m.Called()

	var r0 *mysql.UserRepository
	if rf, ok := ret.Get(0).(func() *mysql.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mysql.UserRepository)
		}
	}

	return r0
}

// Update provides a mock function with given fields: ctx, data, id
func (_m *RepoUserCreational) Update(ctx context.Context, data *entity.User, id int) error {
	ret := _m.Called(ctx, data, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, int) error); ok {
		r0 = rf(ctx, data, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepoUserCreational creates a new instance of RepoUserCreational. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoUserCreational(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoUserCreational {
	mock := &RepoUserCreational{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
