// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	entity "bacakomik/record/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMangaCreational is an autogenerated mock type for the ServiceMangaCreational type
type ServiceMangaCreational struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *ServiceMangaCreational) Create(ctx context.Context, data *entity.Manga) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Manga) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *ServiceMangaCreational) GetAll(ctx context.Context) []*entity.Manga {
	ret := _m.Called(ctx)

	var r0 []*entity.Manga
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Manga); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Manga)
		}
	}

	return r0
}

// GetOne provides a mock function with given fields: ctx, id
func (_m *ServiceMangaCreational) GetOne(ctx context.Context, id int) *entity.Manga {
	ret := _m.Called(ctx, id)

	var r0 *entity.Manga
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Manga); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Manga)
		}
	}

	return r0
}

// Update provides a mock function with given fields: ctx, data, id
func (_m *ServiceMangaCreational) Update(ctx context.Context, data *entity.Manga, id int) error {
	ret := _m.Called(ctx, data, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Manga, int) error); ok {
		r0 = rf(ctx, data, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceMangaCreational creates a new instance of ServiceMangaCreational. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMangaCreational(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMangaCreational {
	mock := &ServiceMangaCreational{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
