basePath: /
definitions:
  entity.Manga:
    properties:
      author:
        type: string
      created_at:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      release_date:
        type: string
      sinopsis:
        type: string
      status:
        type: string
      title:
        type: string
      total_chapter:
        type: integer
      type:
        type: string
    type: object
  model.CreateMangaRequest:
    properties:
      author:
        type: string
      release_date:
        type: string
      sinopsis:
        type: string
      status:
        type: string
      title:
        type: string
      total_chapter:
        type: integer
      type:
        type: string
    type: object
  model.Response:
    properties:
      data: {}
      error_code:
        type: integer
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: hanan@asyrawih.id
    name: API manga
  description: Manga service api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hanan Test
  version: 1.0.0
paths:
  /manga:
    get:
      consumes:
      - application/json
      description: get all manga
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.Manga'
                  type: array
              type: object
      summary: List manga
      tags:
      - manga
    post:
      consumes:
      - application/json
      description: create manga by accept body json
      parameters:
      - description: manga requested info
        in: body
        name: manga
        required: true
        schema:
          $ref: '#/definitions/model.CreateMangaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.Manga'
              type: object
      summary: create manga
      tags:
      - manga
  /manga/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Manga based on id
      parameters:
      - description: Manga Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Remove manga
      tags:
      - manga
    get:
      consumes:
      - application/json
      description: get all manga
      parameters:
      - description: Manga Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/entity.Manga'
              type: object
      summary: List manga
      tags:
      - manga
    put:
      consumes:
      - application/json
      description: update manga by pass id
      parameters:
      - description: Manga Id
        in: path
        name: id
        required: true
        type: integer
      - description: manga requested info
        in: body
        name: manga
        required: true
        schema:
          $ref: '#/definitions/model.CreateMangaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Update Manga
      tags:
      - manga
swagger: "2.0"
